version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "3001:3001"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    command: "air"

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysqldbvolume:/var/lib/mysql
  migrate:
    image: migrate/migrate
    depends_on:
      - db
    volumes:
      - ./migrations:/migrations
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "mysql://${DB_USER}:${DB_PASSWORD}@tcp(db:3306)/${DB_NAME}?query",
        "up"
      ]
  # nsqlookupd:
  #   image: nsqio/nsq
  #   command: /nsqlookupd
  #   ports:
  #     - "4160:4160"
  #     - "4161:4161"

  # nsqd:
  #   image: nsqio/nsq
  #   command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
  #   depends_on:
  #     - nsqlookupd
  #   ports:
  #     - "4150:4150"
  #     - "4151:4151"

  # nsqadmin:
  #   image: nsqio/nsq
  #   command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
  #   depends_on:
  #     - nsqlookupd
  #   ports:
  #     - "4171:4171"
volumes:
  mysqldbvolume:
    driver: local
